# Generated by Django 2.0.5 on 2018-06-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='comentario',
            field=models.CharField(blank=True, default='NO HAY COMENTARIO', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
